### ISSUE TITLE
能提供下摔倒识别的模型吗？STGCN.ONNX

### ISSUE THREAD

**Issue by liujb1314** [guojin-yan/Csharp_and_OpenVINO_deploy_PP-Human#1]
老师，我尝试从飞浆进行模型转化，但初始化时出现错误，您能给一下摔倒识别的ONNX模型吗？

**Comment by liujb1314** [comment]
- [ ] ![image](https://user-images.githubusercontent.com/10348926/230554011-6d84fbb3-d7d4-4677-bb9d-73aba6c3f903.png)
- [ ] 
![image](https://user-images.githubusercontent.com/10348926/230554094-b1f0298b-9635-45c2-8929-7d1acff5a51d.png)

老师，我从Paddle下载的STGCN模型，重新设置了下shap，预测时发生以上异常，您能帮忙看看吗

**Comment by guojin-yan** [comment]
刚看到你的问题，应该是数据长度有问题，如果有问题可以加我的微信GitGitee
